# Use an official node image as a base
FROM node:22.1.0

# Create and set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY ./package.json ./

# Install dependencies
RUN npm install

# Copy rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Run the app
CMD ["npm", "start"]
