version: '3.7'
services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile

    container_name: client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: dockerfile

    container_name: server
    ports:
      - "5000:5000"
    env_file: ./server/.env
    environment:
      NODE_ENV: development
