version: "3"
services:
  react-app:
    build:
      context: ./client
    stdin_open: true
    ports: 
      - "3000:3000"
  api-server:
    build:
      context: ./server
    ports:
      - "5000:5000"