services:
  server:
    build:
      context: ./server
    environment:
      NODE_ENV: development
    ports:
      - 3500:3500
  client:
    build:
        context: ./client
    environment:
       NODE_ENV: development
    ports:
      - 3000:3000