# Use an official Node.js image as a base
FROM node:22-alpine3.19

# Set working directory
WORKDIR /app/server

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port (if necessary)
EXPOSE 3500

# Command to run the server
CMD ["node", "server.js"]