# Use an official node image as a base
FROM mhart/alpine-node:8.11.4

# Create and set working directory
WORKDIR /api

# Copy package.json and package-lock.json
COPY package*.json /api/

# Install dependencies
RUN npm install

# Copy rest of the application code
COPY . /api/

# Expose the port the app runs on
EXPOSE 80

# Start the application
CMD ["npm", "run", "dev"]
